import './js/one-page-scroll.js';
import './js/menu.js';
import './js/fs-menu.js';
import './js/team.js';
import './js/reviews.js';
import './js/form.js';
import './js/slider.js';
import './js/video.js';
import './js/map.js';
